import { type DataRelation } from "./data-rights-policy.types"

export const SECONDARY_DATA_RELATIONS: readonly DataRelation[] = [
	{
		table: "provider_completions",
		identifiers: ["learner_address"],
		deletion: "anonymise",
		description: "Provider completion records",
	},
	{
		table: "lrn_burns",
		identifiers: ["wallet_address"],
		deletion: "anonymise",
		description: "Public LRN burn records",
	},
	{
		table: "identity_verifications",
		identifiers: ["wallet_address"],
		deletion: "erase",
		description: "KYC and anti-sybil artifacts",
	},
	{
		table: "certificates",
		identifiers: ["user_id"],
		deletion: "anonymise",
		description: "Credential certificates",
	},
	{
		table: "mentor_bookings",
		identifiers: ["learner_addr", "mentor_addr"],
		deletion: "erase",
		description: "Mentor bookings",
	},
	{
		table: "mentor_availability",
		identifiers: ["mentor_addr"],
		deletion: "erase",
		description: "Mentor availability",
	},
	{
		table: "mentors",
		identifiers: ["address"],
		deletion: "erase",
		description: "Mentor account profile",
	},
	{
		table: "qf_contributions",
		identifiers: ["donor_addr"],
		deletion: "anonymise",
		description: "Public quadratic funding contributions",
	},
	{
		table: "bounties",
		identifiers: ["sponsor_addr"],
		deletion: "anonymise",
		description: "Public bounties sponsored by the learner",
	},
	{
		table: "bounty_submissions",
		identifiers: ["learner_addr"],
		deletion: "anonymise",
		description: "Public bounty submissions",
	},
	{
		table: "learner_streaks",
		identifiers: ["learner_address"],
		deletion: "erase",
		description: "Learning streak aggregate",
	},
	{
		table: "streak_activity",
		identifiers: ["learner_address"],
		deletion: "erase",
		description: "Learning streak activity",
	},
	{
		table: "referrals",
		identifiers: ["referrer_addr", "referred_addr"],
		deletion: "erase",
		description: "Referral relationships",
	},
	{
		table: "escrows",
		identifiers: ["scholar_address"],
		deletion: "anonymise",
		description: "Public scholarship escrow mirror",
	},
	{
		table: "passkey_credentials",
		identifiers: ["contract_address"],
		deletion: "erase",
		description: "Passkey authentication credentials",
	},
	{
		table: "anchor_withdrawals",
		identifiers: ["learner_addr"],
		deletion: "erase",
		description: "Withdrawal requests and KYC status",
	},
	{
		table: "sponsored_accounts",
		identifiers: ["learner_address"],
		deletion: "anonymise",
		description: "Public sponsored account records",
	},
	{
		table: "sponsor_spend_log",
		identifiers: ["learner_address"],
		deletion: "anonymise",
		description: "Sponsor aggregate spending log",
	},
	{
		table: "translator_grants",
		identifiers: ["wallet_address"],
		deletion: "erase",
		description: "Translation permissions",
	},
	{
		table: "course_translations",
		identifiers: ["translator_address", "reviewed_by_address"],
		deletion: "anonymise",
		description: "Course translations and reviews",
	},
	{
		table: "lesson_translations",
		identifiers: ["translator_address", "reviewed_by_address"],
		deletion: "anonymise",
		description: "Lesson translations and reviews",
	},
	{
		table: "treasury_deposits",
		identifiers: ["donor_address"],
		deletion: "anonymise",
		description: "Public treasury deposits",
	},
	{
		table: "disputes",
		identifiers: ["scholar_address"],
		deletion: "anonymise",
		description: "Milestone disputes",
	},
	{
		table: "dispute_jurors",
		identifiers: ["juror_address"],
		deletion: "anonymise",
		description: "Dispute jury assignments",
	},
	{
		table: "dispute_votes",
		identifiers: ["juror_address"],
		deletion: "anonymise",
		description: "Dispute jury votes",
	},
	{
		table: "pending_dispute_evidence",
		identifiers: ["scholar_address"],
		deletion: "erase",
		description: "Pending dispute evidence",
	},
] as const
