/// <reference lib="webworker" />
import { CacheableResponsePlugin } from "workbox-cacheable-response"
import { clientsClaim } from "workbox-core"
import { ExpirationPlugin } from "workbox-expiration"
import { precacheAndRoute } from "workbox-precaching"
import { registerRoute } from "workbox-routing"
import { NetworkFirst, StaleWhileRevalidate } from "workbox-strategies"

declare const self: ServiceWorkerGlobalScope

void clientsClaim()

// Precache all assets generated by the build.
// The manifest is injected by vite-plugin-pwa / workbox-webpack-plugin.
precacheAndRoute(self.__WB_MANIFEST)

// ── Runtime caching ──────────────────────────────────────────────────────────

// Stale-while-revalidate for course catalog and detail (content rarely changes,
// but should still load fast from cache on revisit).
registerRoute(
	({ url }) =>
		url.pathname === "/api/courses" ||
		/^\/api\/courses\/[^/]+$/.test(url.pathname),
	new StaleWhileRevalidate({
		cacheName: "learnvault-courses",
		plugins: [
			new CacheableResponsePlugin({ statuses: [0, 200] }),
			new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 }),
		],
	}),
)

// Network-first for live / user-specific data (streaks, leaderboard, scholar
// data, enrolled courses). If the network is unavailable we fall back to cache
// but never serve stale data as the primary source.
registerRoute(
	({ url }) =>
		url.pathname.startsWith("/api/streaks") ||
		url.pathname.startsWith("/api/scholars") ||
		url.pathname === "/api/courses/enrolled" ||
		url.pathname.startsWith("/api/me/"),
	new NetworkFirst({
		cacheName: "learnvault-live",
		networkTimeoutSeconds: 5,
		plugins: [
			new CacheableResponsePlugin({ statuses: [0, 200] }),
			new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 60 * 60 }),
		],
	}),
)

// ── Offline cache for downloaded tracks ──────────────────────────────────────
// Track-level caches (learnvault-track-{slug}) are created and managed
// entirely by the frontend via Cache Storage API. The service worker just
// ensures that same-origin GET requests can be served from any cache.

// ── Navigation fallback ──────────────────────────────────────────────────────
// SPA fallback: any navigation request that isn't for /api/* or static assets
// gets the cached index.html.
const NAVIGATION_FALLBACK = "/index.html"
const NAVIGATION_DENYLIST = [/^\/api\//]

self.addEventListener("fetch", (event) => {
	if (event.request.mode !== "navigate") return
	if (NAVIGATION_DENYLIST.some((re) => re.test(event.request.url))) return

	event.respondWith(
		(async () => {
			try {
				const networkResponse = await fetch(event.request)
				// Keep a fresh copy in the precache for next offline load
				const cache = await caches.open("learnvault-navigations")
				void cache.put(event.request, networkResponse.clone())
				return networkResponse
			} catch {
				const cache = await caches.open("learnvault-navigations")
				const cached = await cache.match(NAVIGATION_FALLBACK)
				return cached ?? Response.error()
			}
		})(),
	)
})

// ── Cache cleanup on activate ────────────────────────────────────────────────
const CURRENT_CACHES = new Set([
	"learnvault-precache",
	"learnvault-courses",
	"learnvault-live",
	"learnvault-navigations",
])

self.addEventListener("activate", (event) => {
	event.waitUntil(
		caches
			.keys()
			.then((names) =>
				Promise.all(
					names
						.filter(
							(name) =>
								!CURRENT_CACHES.has(name) && !name.startsWith("learnvault-track-"),
						)
						.map((name) => caches.delete(name)),
				),
			)
			.then(() => self.clients.claim()),
	)
})

// ── Message handling ─────────────────────────────────────────────────────────
// Allow the app to send a message to the SW to skip waiting.
self.addEventListener("message", (event) => {
	if (event.data?.type === "SKIP_WAITING") {
		void self.skipWaiting()
	}
})
